github.client.id=9d5e13ac2f6608c3cfcb
github.client.secret=3d9495f9bde0c25973534818cd30f41e3472c4ed
github.redirect.uri=http://localhost:8080/callback


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/community?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123

# ¿ªÆôÍÕ·å±êÊ¶
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.yeexang.community.pojo
mybatis.mapper-locations=classpath:mapper/*.xml
