server:
  port: 8080
  servlet:
    context-path: /community

spring:
  application:
    name: community
  mvc:
    view:
      prefix: classpath:/templates/   # 定位模板的目录
      suffix: .html   # 给返回的页面添加后缀名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/community_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml   # 扫描映射配置文件
  type-aliases-package: com.styeeqan.community.entity  # 别名
  configuration:
    map-underscore-to-camel-case: true  # 驼峰标识

pagehelper:
  reasonable: true  # 合理化参数

logging:
  level:
    com.styeeqan.community.mapper: debug   # 开启 sql 日志

# jwt 密钥
jwt:
  token-secret: community_token#$%Abc

# 阿里云 oss 参数
aliyun:
  oss:
    endpoint: aaaaaaaaaaaaaaaaa
    accessKeyId: aaaaaaaaaaaaaaaaaaa
    accessKeySecret: aaaaaaaaaaaaaaaaa
    bucketName: aaaaaaaaaa