server:
  port: 8080
  servlet:
    context-path: /yeexang-community

spring:
  application:
    name: yeexang-community
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeexang_community_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰标识
  mapper-locations: classpath:/mapper/*.xml   # 扫描映射配置文件
  type-aliases-package: com.yeexang.community.entity  # 别名

logging:
  level:
    com.yeexang.community.dao: debug   # 开启 sql 日志

# 请求白名单
interceptor:
  token-white-request-uri: /yeexang-community/user/login,/yeexang-community/user/register,/yeexang-community/topic/page,/yeexang-community/comment/list,/yeexang-community/section/list,/yeexang-community/topic/visit,/yeexang-community/notification/announcement

# jwt 密钥
jwt:
  token-secret: community_token#$%Abc

# 合理化参数
pagehelper:
  reasonable: true

# 阿里云 oss 参数
aliyun:
  oss:
    endpoint: oss-cn-shenzhen-internal.aliyuncs.com
    accessKeyId: LTAI5tMd7SjJnkKaMSarpUuN
    accessKeySecret: axBtFZW5JHC3KmIZvJfNWVu2ZYBi6y
    bucketName: comubucket