github.client.id=9d5e13ac2f6608c3cfcb
github.client.secret=d2746b92bc23c9726e145179ee96c99fe574a75c
github.redirect.uri=http://localhost:8080/callback

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:G:/Java/WP/community/h2database
spring.datasource.username=root
spring.datasource.password=123