server:
  port: 8080

spring:
  application:
    name: yeexang-community
  mvc:
    view:
      prefix: classpath:/templates/   # 定位模板的目录
      suffix: .html   # 给返回的页面添加后缀名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeexang_community_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useAffectedRows=true
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰标识
  mapper-locations: classpath:/mapper/*.xml   # 扫描映射配置文件
  type-aliases-package: com.yeexang.community.entity  # 别名

logging:
  level:
    com.yeexang.community.dao: debug   # 开启 sql 日志

# jwt 密钥
jwt:
  token-secret: community_token#$%Abc

# 合理化参数
pagehelper:
  reasonable: true

# 阿里云 oss 参数
aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: aaaaaaaaaa
    accessKeySecret: aaaaaaaaaaaaa
    bucketName: comubucket